#!/bin/bash
# Blender Installation Guide for macOS

echo "🎨 Blender Installation Guide"
echo "=============================="
echo ""
echo "1. Download Blender:"
echo "   https://www.blender.org/download/"
echo "   Download: macOS (Apple Silicon) - Blender 4.3 or later"
echo ""
echo "2. Install Blender:"
echo "   - Open the downloaded .dmg file"
echo "   - Drag Blender.app to /Applications/"
echo ""
echo "3. Create command-line symlink:"
echo "   Run this command to make 'blender' available in terminal:"
echo ""
echo "   sudo ln -s /Applications/Blender.app/Contents/MacOS/Blender /usr/local/bin/blender"
echo ""
echo "4. Verify installation:"
echo "   blender --version"
echo ""
echo "=============================="
echo ""
echo "After installation, come back here and we'll test the rendering!"
