CREATE TABLE IF NOT EXISTS featureFlags (
  `key` VARCHAR(128) PRIMARY KEY,
  enabled INT NOT NULL DEFAULT 1,
  description TEXT NULL,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pricingRules (
  `key` VARCHAR(64) PRIMARY KEY,
  costCents INT NOT NULL DEFAULT 0,
  priceCents INT NOT NULL DEFAULT 0,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS adminSettings (
  `key` VARCHAR(64) PRIMARY KEY,
  value TEXT NOT NULL,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alerts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  level ENUM('info','warning','critical') NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  jobId VARCHAR(64) NULL,
  userId INT NULL,
  error TEXT NULL,
  action TEXT NULL,
  costCents INT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
