ALTER TABLE users
  ADD COLUMN encryptedApiKeys TEXT NULL;

CREATE TABLE IF NOT EXISTS jobs (
  id VARCHAR(64) PRIMARY KEY,
  userId INT NOT NULL,
  status ENUM('queued','processing','completed','failed') NOT NULL DEFAULT 'queued',
  inputUrl TEXT NOT NULL,
  operations TEXT NOT NULL,
  currentStep INT NOT NULL DEFAULT 0,
  outputUrl TEXT NULL,
  stepResults TEXT NULL,
  error TEXT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  completedAt TIMESTAMP NULL
);
